name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install node modules
      run: npm ci

    - name: Compile TypeScript
      run: npm run compile

    - name: Lint
      run: npm run lint

    - name: Tests
      run: npm run test


  build_android:
    needs: ["test"]
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Build dist files
      run: |
        npm ci
        npm run build

    - name: Install node_modules
      working-directory: DemoApp
      run: |
        yarn install --frozen-lockfile --network-timeout 100000

    - name: Lint DemoApp
      working-directory: DemoApp
      run: yarn lint

    - name: Build DemoApp
      working-directory: DemoApp/android
      run: |
        ./gradlew assembleDebug

  build_ios:
    needs: ["test"]
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Build dist files
      run: |
        npm ci
        npm run build

    - name: Install node_modules
      working-directory: DemoApp
      run: |
        yarn install --frozen-lockfile --network-timeout 100000

    - name: Install Pods
      working-directory: DemoApp/ios
      run: |
        pod install

    - name: Build DemoApp
      working-directory: DemoApp/ios
      run: |
        xcodebuild \
          -workspace DemoApp.xcworkspace \
          -scheme DemoApp \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 12' \
          -derivedDataPath ios/build -UseModernBuildSystem=YES \
          clean build \
          CODE_SIGNING_ALLOWED=NO

  publish_npm:
    needs: ["build_android", "build_ios"]
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'

    - name: Build dist files
      run: |
        npm ci
        npm run build

    - name: NPM Publish
      run: |
        if [[ "${{ needs.version_check.outputs.v_tracker }}" = *-* ]] ; then
          npm publish --access public --tag next
        else
          npm publish --access public
        fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    needs: ["publish_npm"]
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Release
      uses: softprops/action-gh-release@v0.1.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Version ${{ needs.version_check.outputs.v_tracker }}
        draft: false
        prerelease: ${{ contains(needs.version_check.outputs.v_tracker, '-') }}
